name: GitHub Actions Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches-ignore:
      - main
      - renovate/*
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  Publish-Preview:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
          registry-url: "https://registry.npmjs.org"
      - name: Install Dependencies
        run: npm install
      - name: Build project
        run: npm run build
      - name: Test project
        run: npm test
      - name: Copy readme
        run: cp README.md packages/nativewind/
      - name: Version
        id: version
        working-directory: ./packages/nativewind
        run: npm version prerelease --preid $(git describe --tags --always) --no-git-tag-version && echo "version=$(jq -r .version package.json)" >> $GITHUB_OUTPUT
      - name: Publish
        working-directory: ./packages/nativewind
        run: npm publish --tag preview
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  Deploy-Preview:
    runs-on: ubuntu-latest
    needs: [Publish-Preview]
    outputs:
      vercel_url: ${{ steps.deploy.outputs.vercel_url }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Install Preview Nativewind
        run: npm install nativewind@${{ needs.Publish-Preview.outputs.version }} -w website
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        id: deploy
        run: echo "vercel_url=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})" >> $GITHUB_OUTPUT

  Snackager:
    runs-on: ubuntu-latest
    needs: [Publish-Preview]
    steps:
      - name: Update Snackager
        run: sleep 45 && curl "https://snackager.expo.io/bundle/nativewind@${{ needs.Publish-Preview.outputs.version }}?platforms=ios,android,web&version_snackager=true&bypassCache=true" --retry 5

  Expo-Snack:
    runs-on: ubuntu-latest
    needs: [Deploy-Preview, Publish-Preview]
    steps:
      - name: Create comment
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const files = encodeURIComponent(JSON.stringify({
              "App.tsx": {
                "type": "CODE",
                "contents": `import React from "react";
            import { withExpoSnack } from "nativewind";
            import { Text, View } from "react-native";
            import { styled } from "nativewind";

            const StyledView = styled(View);
            const StyledText = styled(Text);

            function App () {
              return (
                <StyledView className="flex-1 items-center justify-center">
                  <StyledText className="text-slate-800">Try editing me! 🎉</StyledText>
                </StyledView>
              );
            };

            // This demo is using a external compiler that will only work in Expo Snacks.
            // You may see flashes of unstyled content, this will not occur under normal use!
            // Please see the documentation to setup your application
            export default withExpoSnack(App, {
              compileUrl: "${{ needs.Deploy-Preview.outputs.vercel_url }}/api/compile"
            });`
              }
            }));
            const body = `
              Version: ${{ needs.Publish-Preview.outputs.version }}
              Docs: ${{ needs.Deploy-Preview.outputs.vercel_url }}
              Snack: https://snack.expo.dev?dependencies=nativewind%40${{ needs.Publish-Preview.outputs.version }}&files=${files}
            `;
            github.rest.repos.createCommitComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: "${{ github.sha }}",
              body
            })
