name: GitHub Actions Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches-ignore:
      - main
      - renovate/*
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.deploy.outputs.vercel_url }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        id: deploy
        run: echo "vercel_url=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})" >> $GITHUB_OUTPUT

  Publish-Preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
      - name: Install Dependencies
        run: npm install
      - name: Build project
        run: npm run build
      - name: Test project
        run: npm test
      - name: Copy readme
        run: cp README.md packages/nativewind/
      - name: Version
        run: npm version $(git describe --tags) --no-git-tag-version
      - name: Publish
        run: npm publish --tag preview
      - name: Snackager
        run: sleep 45 && curl "https://snackager.expo.io/bundle/nativewind@$(git describe --tags)?platforms=ios,android,web&version_snackager=true&bypassCache=true" --retry 5

  Expo-Snack:
    runs-on: ubuntu-latest
    needs: [Deploy-Preview, Publish-Preview]
    steps:
      - name:
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.repos.createCommitComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: $GITHUB_SHA,
              body: "${{ needs.Deploy-Preview.outputs.vercel_url }}"
            })
